
import { FlutterAbility, FlutterEngine } from '@ohos/flutter_ohos';
import FlutterLocPlugin from '../plugins/FlutterLocPlugin';
import { GeneratedPluginRegistrant } from '../plugins/GeneratedPluginRegistrant';

export default class EntryAbility extends FlutterAbility {
  configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    GeneratedPluginRegistrant.registerWith(flutterEngine)
    flutterEngine.getPlugins()?.add(new FlutterLocPlugin())

  }
}
